coverage:
  precision: 2         # how many decimal places to display in the UI: 0 <= value <= 4
  round: down          # how coverage is rounded: down/up/nearest
  range: 80...100      # custom range of coverage colors from red -> yellow -> green

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: 90%            # specify the target coverage for each commit status

    patch:                     # pull requests only: this commit status will measure the
      # entire pull requests Coverage Diff. Checking if the lines
      # adjusted are covered at least X%.
      default:
        enabled: yes             # must be yes|true to enable this status
        target: 95%              # specify the target "X%" coverage to hit
        branches: null           # -> see "branch patterns" below
        threshold: null          # allowed to drop X% and still result in a "success" commit status
        if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded
        # options: success, error, failure
        if_not_found: success
        if_ci_failed: error


  ignore:          # files and folders that will be removed during processing
    - "**/*_mock.go"
    - "**/*_test.go"