linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - wrapcheck
    - gofumpt
    - gci
    - godox
    - deadcode # TODO remove this. This is just for now
  #deprecated
    - scopelint
    - maligned
    - interfacer
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
        - goconst
    - path: _mock\.go
      linters:
        - dupl
        - gomnd
        - forcetypeassert
